name: anntraining
channels:
  - conda-forge
  - nodefaults
  - cadwr-dms
dependencies:
  - python==3.9 # 3.9 is max for tensorflow 2.7.4
  - pip
  - ipykernel
  #- tensorflow==2.7.4               #Install after using pip. See commented command below
  - vtools3>=3.7.5
  - dms-datastore>=0.1.0 
  - numpy>=1.20,<2  
  - pandas>=2    
  - scikit-learn
  - keras
  #- keras-tuner                     # Install afterwards using pip. See commented command below
  - tabulate
  - pandas
  - openpyxl
  - xlrd # [version='>=1.0.0']
  - statsmodels
  - bokeh
  - hvplot
  - holoviews
  - panel
  - pyhecdss
  - ipykernel
  - openpyxl==3.1.0

# pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org tensorflow==2.7.4
# pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org keras-tuner

